name: Deploy to VPS

# Se activa cada vez que haces push a la rama 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            # Navega a la carpeta del proyecto
            cd ~/app
            # Descarga los últimos cambios de GitHub
            git pull origin main
            # Reconstruye el contenedor Docker
            docker build -t mi-sitio-web .
            # Detiene y elimina el contenedor antiguo si existe
            docker stop web-container || true
            docker rm web-container || true
            # Lanza el nuevo contenedor
            docker run -d -p 8080:80 --name web-container mi-sitio-web